coverage:
    range: 70..100
    round: down
    status:
        project:
            default:                
                target: 100%
        patch:
            default:
              target: 90%
ignore:      
    - "src/index.tsx"